version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: apt-get update && apt-get install -y wget libncursesw5-dev
      - run:
          name: Setup
          command: wget https://github.com/commercialhaskell/stack/releases/download/v1.2.0/stack-1.2.0-linux-x86_64.tar.gz -O /tmp/stack.tar.gz && mkdir /tmp/stack/ && tar -xvzf /tmp/stack.tar.gz -C /tmp/stack/ && mv /tmp/stack/stack-1.2.0-linux-x86_64/stack /usr/bin/stack && stack upgrade
      - run:
          name: Build
          command: stack setup && stack build
