version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: apt-get update && apt-get install -y wget libncursesw5-dev
      - run:
          name: Setup
          command: wget -qO- https://get.haskellstack.org/ | sh
      - run:
          name: Build
          command: stack setup && stack build
