version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Install Deps
          command: apt-get update && apt-get install -y wget libncursesw5-dev
      - run:
          name: Install Stack
          command: wget -qO- https://get.haskellstack.org/ | sh
      - run:
          name: Setup
          command: stack setup
      - save_cache:
          paths:
            - ~/.stack
          key: cache-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Build
          command: stack build
